### ISSUE TITLE
Path being doubled when running on windows

### ISSUE THREAD

**Issue by SeanSobeySage** [jrnewell/gulp-min-map#1]
Hi, thanks for the great plugin.

I think I have found an issue when running this on windows:

This:
'script src="/lib/jquery/jquery.js"'
gets transformed to this:
'script src="\lib\jquery\lib\jquery\jquery.min.js"'

It seems this is happening because, in the check on your line 73 (minFile.indexOf(path.sep) == 0) fails as path.sep is '\'.

But maybe the line 78 is actually a bug as well because it then replaces the original 'jquery.js' with the full min path 'lib\jquery\jquery.min.js'. (return replaceLastInstance(srcFile, path.basename(srcFile), minFile);) This is causing the doubling.

This is not what the comment above it implies, and changing it to:
return replaceLastInstance(srcFile, path.basename(srcFile), path.basename(minFile));
fixes the issue.

Is this correct?

Thanks

**Comment by jrnewell** [comment]
Go catch... I guess I forgot that Windows uses a different set of path utility functions than Linux/OS X.  I am kind of abusing the fact that the posix file path handling is basically the same for URLs.  I will put in a fix to force the use of posix path handling.

It has been a while since I looked at this, but I don't think that line is a bug per se.  I think your duplication issue stems from the fact that it is using the window path functions.  I think I didn't include a path.basename call for `minFile` because it allows one to be specify a different relative path for the min file if one wants to.

**Comment by SeanSobeySage** [comment]
Thanks for the reply.

Yeah the posix handling makes sense, I look forward to fix.

**Comment by jrnewell** [comment]
It should be already fixed.  Just upgrade the package and let me know how it goes.

**Comment by SeanSobeySage** [comment]
Yeah latest version works! Thanks for you help.
